In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns

import pandas as pd
import numpy as np
from pylab import rcParams

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, precision_recall_curve
from sklearn.metrics import recall_score, classification_report, auc, roc_curve
from sklearn.metrics import precision_recall_fscore_support, f1_score



# import metrics to compute accuracy
from sklearn.metrics import accuracy_score


from numpy.random import seed
seed(7)

from sklearn.model_selection import train_test_split

SEED = 123 #used to help randomly select the data points
DATA_SPLIT_PCT = 0.2

rcParams['figure.figsize'] = 8, 6
LABELS = ["Normal","Break"]

In [2]:
df = pd.read_csv("processed_data18.csv") 
df.head(n=5)  # visualize the data.

Unnamed: 0         time  y        x1        x2        x3         x4  \
0           0  5/1/99 0:00  0  0.376665 -4.596435 -4.095756  13.497687   
1           1  5/1/99 0:02  0  0.475720 -4.542502 -4.018359  16.230659   
2           2  5/1/99 0:04  0  0.363848 -4.681394 -4.353147  14.127997   
3           3  5/1/99 0:06  0  0.301590 -4.758934 -4.023612  13.161566   
4           4  5/1/99 0:08  0  0.265578 -4.749928 -4.333150  15.267340   

         x5         x6        x7  ...  trend_x52  trend_x53  trend_x54  \
0 -0.118830 -20.669883  0.000732  ...        NaN        NaN        NaN   
1 -0.128733 -18.758079  0.000732  ...        NaN        NaN        NaN   
2 -0.138636 -17.836632  0.010803  ...        NaN        NaN        NaN   
3 -0.148142 -18.517601  0.002075  ...        NaN        NaN        NaN   
4 -0.155314 -17.505913  0.000732  ...        NaN        NaN        NaN   

   trend_x55  trend_x56  trend_x57  trend_x58  trend_x59  trend_x60  trend_x61  
0        NaN        NaN        NaN        NaN        NaN        NaN        NaN  
1        NaN        NaN        NaN        NaN        NaN        NaN        NaN  
2        NaN        NaN        NaN        NaN        NaN        NaN        NaN  
3        NaN        NaN        NaN        NaN        NaN        NaN        NaN  
4        NaN        NaN        NaN        NaN        NaN        NaN        NaN  

[5 rows x 612 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18398 entries, 0 to 18397
Columns: 612 entries, Unnamed: 0 to trend_x61
dtypes: float64(600), int64(11), object(1)
memory usage: 85.9+ MB


In [4]:
# Remove time column
df = df.drop(['time','x28','x61','trend_x61'], axis=1)


In [5]:
df.replace([np.inf, -np.inf], 0, inplace=True)
df

Unnamed: 0  y        x1        x2        x3          x4        x5  \
0               0  0  0.376665 -4.596435 -4.095756   13.497687 -0.118830   
1               1  0  0.475720 -4.542502 -4.018359   16.230659 -0.128733   
2               2  0  0.363848 -4.681394 -4.353147   14.127997 -0.138636   
3               3  0  0.301590 -4.758934 -4.023612   13.161566 -0.148142   
4               4  0  0.265578 -4.749928 -4.333150   15.267340 -0.155314   
...           ... ..       ...       ...       ...         ...       ...   
18393       18393  0 -0.877441  0.786430  0.406426  135.301215  0.112295   
18394       18394  0 -0.843988  0.633086  0.561918  133.228949  0.141332   
18395       18395  0 -0.826547  0.450126  0.334582  134.977973  0.170370   
18396       18396  0 -0.822843  0.419383  0.387263  135.658942  0.199422   
18397       18397  0 -0.840981  0.582710  0.593416  136.339880  0.228460   

              x6        x7        x8  ...  trend_x51  trend_x52  trend_x53  \
0     -20.669883  0.000732 -0.061114  ...        NaN        NaN        NaN   
1     -18.758079  0.000732 -0.061114  ...        NaN        NaN        NaN   
2     -17.836632  0.010803 -0.061114  ...        NaN        NaN        NaN   
3     -18.517601  0.002075 -0.061114  ...        NaN        NaN        NaN   
4     -17.505913  0.000732 -0.061114  ...        NaN        NaN        NaN   
...          ...       ...       ...  ...        ...        ...        ...   
18393  26.300392 -0.159185  0.058823  ...        NaN        NaN        NaN   
18394  25.678597 -0.159185  0.058823  ...        NaN        NaN        NaN   
18395  25.056801 -0.159185  0.048752  ...        NaN        NaN        NaN   
18396  24.435005 -0.159185  0.048752  ...        NaN        NaN        NaN   
18397  24.712960 -0.159185  0.048752  ...        NaN        NaN        NaN   

       trend_x54  trend_x55  trend_x56  trend_x57  trend_x58  trend_x59  \
0            NaN        NaN        NaN        NaN        NaN        NaN   
1            NaN        NaN        NaN        NaN        NaN        NaN   
2            NaN        NaN        NaN        NaN        NaN        NaN   
3            NaN        NaN        NaN        NaN        NaN        NaN   
4            NaN        NaN        NaN        NaN        NaN        NaN   
...          ...        ...        ...        ...        ...        ...   
18393        NaN        NaN        NaN        NaN        NaN        NaN   
18394        NaN        NaN        NaN        NaN        NaN        NaN   
18395        NaN        NaN        NaN        NaN        NaN        NaN   
18396        NaN        NaN        NaN        NaN        NaN        NaN   
18397        NaN        NaN        NaN        NaN        NaN        NaN   

       trend_x60  
0            NaN  
1            NaN  
2            NaN  
3            NaN  
4            NaN  
...          ...  
18393        NaN  
18394        NaN  
18395        NaN  
18396        NaN  
18397        NaN  

[18398 rows x 608 columns]

In [6]:
X = df.drop(['y'], axis=1)
y = df['y']

In [7]:
X
X=X.fillna(0)
X

Unnamed: 0        x1        x2        x3          x4        x5  \
0               0  0.376665 -4.596435 -4.095756   13.497687 -0.118830   
1               1  0.475720 -4.542502 -4.018359   16.230659 -0.128733   
2               2  0.363848 -4.681394 -4.353147   14.127997 -0.138636   
3               3  0.301590 -4.758934 -4.023612   13.161566 -0.148142   
4               4  0.265578 -4.749928 -4.333150   15.267340 -0.155314   
...           ...       ...       ...       ...         ...       ...   
18393       18393 -0.877441  0.786430  0.406426  135.301215  0.112295   
18394       18394 -0.843988  0.633086  0.561918  133.228949  0.141332   
18395       18395 -0.826547  0.450126  0.334582  134.977973  0.170370   
18396       18396 -0.822843  0.419383  0.387263  135.658942  0.199422   
18397       18397 -0.840981  0.582710  0.593416  136.339880  0.228460   

              x6        x7        x8        x9  ...  trend_x51  trend_x52  \
0     -20.669883  0.000732 -0.061114 -0.059966  ...        0.0        0.0   
1     -18.758079  0.000732 -0.061114 -0.059966  ...        0.0        0.0   
2     -17.836632  0.010803 -0.061114 -0.030057  ...        0.0        0.0   
3     -18.517601  0.002075 -0.061114 -0.019986  ...        0.0        0.0   
4     -17.505913  0.000732 -0.061114 -0.030057  ...        0.0        0.0   
...          ...       ...       ...       ...  ...        ...        ...   
18393  26.300392 -0.159185  0.058823 -0.080108  ...        0.0        0.0   
18394  25.678597 -0.159185  0.058823 -0.080108  ...        0.0        0.0   
18395  25.056801 -0.159185  0.048752 -0.080108  ...        0.0        0.0   
18396  24.435005 -0.159185  0.048752 -0.080108  ...        0.0        0.0   
18397  24.712960 -0.159185  0.048752 -0.070037  ...        0.0        0.0   

       trend_x53  trend_x54  trend_x55  trend_x56  trend_x57  trend_x58  \
0            0.0        0.0        0.0        0.0        0.0        0.0   
1            0.0        0.0        0.0        0.0        0.0        0.0   
2            0.0        0.0        0.0        0.0        0.0        0.0   
3            0.0        0.0        0.0        0.0        0.0        0.0   
4            0.0        0.0        0.0        0.0        0.0        0.0   
...          ...        ...        ...        ...        ...        ...   
18393        0.0        0.0        0.0        0.0        0.0        0.0   
18394        0.0        0.0        0.0        0.0        0.0        0.0   
18395        0.0        0.0        0.0        0.0        0.0        0.0   
18396        0.0        0.0        0.0        0.0        0.0        0.0   
18397        0.0        0.0        0.0        0.0        0.0        0.0   

       trend_x59  trend_x60  
0            0.0        0.0  
1            0.0        0.0  
2            0.0        0.0  
3            0.0        0.0  
4            0.0        0.0  
...          ...        ...  
18393        0.0        0.0  
18394        0.0        0.0  
18395        0.0        0.0  
18396        0.0        0.0  
18397        0.0        0.0  

[18398 rows x 607 columns]

In [8]:
X = X.drop(['Unnamed: 0'], axis=1)


In [9]:
#X=X[['x3','x2','lag_1_x2','lag_1_x3','x2_pct_change','x18','x17','x3_pct_change','x16','rolling_mean_x16','lag_1_x16']]

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
X_train.shape, X_test.shape

((14718, 606), (3680, 606))

In [11]:
# Feature scaling

In [12]:
cols = X_train.columns

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

X_train = pd.DataFrame(X_train, columns=[cols])
X_test = pd.DataFrame(X_test, columns=[cols])


In [13]:
from xgboost import XGBClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from numpy import mean

# define model
model = XGBClassifier()

In [14]:
from imblearn.pipeline import Pipeline

from imblearn.combine import SMOTETomek
from imblearn.under_sampling import TomekLinks


In [15]:
# Define SMOTE-Tomek Links
resample=SMOTETomek(tomek=TomekLinks(sampling_strategy='majority'))
# Define pipeline
pipeline=Pipeline(steps=[('r', resample), ('m', model)])


In [16]:
clf_0 = pipeline.fit(X_train, y_train)


In [17]:
pred_y_0 = clf_0.predict(X_test)

print(accuracy_score(pred_y_0, y_test))



0.9970108695652173


In [18]:
target_names = ['class 0', 'class 1']
print(classification_report(y_test, pred_y_0, target_names=target_names))

# View confusion matrix for test data and predictions
confusion_matrix(y_test, pred_y_0)

              precision    recall  f1-score   support

     class 0       1.00      1.00      1.00      3662
     class 1       0.64      0.89      0.74        18

    accuracy                           1.00      3680
   macro avg       0.82      0.94      0.87      3680
weighted avg       1.00      1.00      1.00      3680



array([[3653,    9],
       [   2,   16]])

In [19]:
#enn

In [20]:
from imblearn.combine import SMOTEENN
from imblearn.under_sampling import EditedNearestNeighbours
# define model
model = XGBClassifier()

#Define SMOTE-ENN
resample=SMOTEENN(enn=EditedNearestNeighbours(sampling_strategy='all'))
#Define pipeline
pipeline=Pipeline(steps=[('r', resample), ('m', model)])

In [21]:
pipeline

Pipeline(steps=[('r',
                 SMOTEENN(enn=EditedNearestNeighbours(sampling_strategy='all'))),
                ('m',
                 XGBClassifier(base_score=None, booster=None, callbacks=None,
                               colsample_bylevel=None, colsample_bynode=None,
                               colsample_bytree=None,
                               early_stopping_rounds=None,
                               enable_categorical=False, eval_metric=None,
                               feature_types=None, gamma=None, gpu_id=None,
                               grow_policy=None, importance_type=None,
                               interaction_constraints=None, learning_rate=None,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=None, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, n_estimators=100,
                               n_jobs=None, num_parallel_tree=None,
                               predictor=None, random_state=None, ...))])

In [22]:
clf_2 = pipeline.fit(X_train, y_train)
pred_y_2 = clf_2.predict(X_test)

print(accuracy_score(pred_y_2, y_test))

0.9959239130434783


In [23]:
target_names = ['class 0', 'class 1']
print(classification_report(y_test, pred_y_2, target_names=target_names))

# View confusion matrix for test data and predictions
confusion_matrix(y_test, pred_y_2)

              precision    recall  f1-score   support

     class 0       1.00      1.00      1.00      3662
     class 1       0.55      0.94      0.69        18

    accuracy                           1.00      3680
   macro avg       0.77      0.97      0.85      3680
weighted avg       1.00      1.00      1.00      3680



array([[3648,   14],
       [   1,   17]])

In [24]:
#ADASYN

from imblearn.over_sampling import ADASYN
ada = ADASYN(random_state=42)
X_res, y_res = ada.fit_resample(X, y)

In [25]:
from collections import Counter
print('Resampled dataset shape %s' % Counter(y_res))

Resampled dataset shape Counter({0: 18274, 1: 18265})


In [26]:
model = XGBClassifier()

#Define ADASYN
resample=ADASYN(random_state=42)
#Define pipeline
pipeline=Pipeline(steps=[('r', resample), ('m', model)])

In [27]:
clf_2 = pipeline.fit(X_train, y_train)
pred_y_2 = clf_2.predict(X_test)

print(accuracy_score(pred_y_2, y_test))

0.9967391304347826


In [28]:
target_names = ['class 0', 'class 1']
print(classification_report(y_test, pred_y_2, target_names=target_names))

# View confusion matrix for test data and predictions
confusion_matrix(y_test, pred_y_2)

              precision    recall  f1-score   support

     class 0       1.00      1.00      1.00      3662
     class 1       0.61      0.94      0.74        18

    accuracy                           1.00      3680
   macro avg       0.80      0.97      0.87      3680
weighted avg       1.00      1.00      1.00      3680



array([[3651,   11],
       [   1,   17]])