In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns

import pandas as pd
import numpy as np
from pylab import rcParams

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, precision_recall_curve
from sklearn.metrics import recall_score, classification_report, auc, roc_curve
from sklearn.metrics import precision_recall_fscore_support, f1_score



# import metrics to compute accuracy
from sklearn.metrics import accuracy_score


from numpy.random import seed
seed(7)

from sklearn.model_selection import train_test_split

SEED = 123 #used to help randomly select the data points
DATA_SPLIT_PCT = 0.2

rcParams['figure.figsize'] = 8, 6
LABELS = ["Normal","Break"]

In [2]:
df = pd.read_csv("processminer-rare-event-mts - data.csv") 
df.head(n=5)  # visualize the data.

time  y        x1        x2        x3         x4        x5  \
0  5/1/99 0:00  0  0.376665 -4.596435 -4.095756  13.497687 -0.118830   
1  5/1/99 0:02  0  0.475720 -4.542502 -4.018359  16.230659 -0.128733   
2  5/1/99 0:04  0  0.363848 -4.681394 -4.353147  14.127997 -0.138636   
3  5/1/99 0:06  0  0.301590 -4.758934 -4.023612  13.161566 -0.148142   
4  5/1/99 0:08  0  0.265578 -4.749928 -4.333150  15.267340 -0.155314   

          x6        x7        x8  ...        x52       x53       x54  \
0 -20.669883  0.000732 -0.061114  ...  10.091721  0.053279 -4.936434   
1 -18.758079  0.000732 -0.061114  ...  10.095871  0.062801 -4.937179   
2 -17.836632  0.010803 -0.061114  ...  10.100265  0.072322 -4.937924   
3 -18.517601  0.002075 -0.061114  ...  10.104660  0.081600 -4.938669   
4 -17.505913  0.000732 -0.061114  ...  10.109054  0.091121 -4.939414   

         x55        x56       x57       x58       x59       x60  x61  
0 -24.590146  18.515436  3.473400  0.033444  0.953219  0.006076    0  
1 -32.413266  22.760065  2.682933  0.033536  1.090502  0.006083    0  
2 -34.183774  27.004663  3.537487  0.033629  1.840540  0.006090    0  
3 -35.954281  21.672449  3.986095  0.033721  2.554880  0.006097    0  
4 -37.724789  21.907251  3.601573  0.033777  1.410494  0.006105    0  

[5 rows x 63 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18398 entries, 0 to 18397
Data columns (total 63 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   time    18398 non-null  object 
 1   y       18398 non-null  int64  
 2   x1      18398 non-null  float64
 3   x2      18398 non-null  float64
 4   x3      18398 non-null  float64
 5   x4      18398 non-null  float64
 6   x5      18398 non-null  float64
 7   x6      18398 non-null  float64
 8   x7      18398 non-null  float64
 9   x8      18398 non-null  float64
 10  x9      18398 non-null  float64
 11  x10     18398 non-null  float64
 12  x11     18398 non-null  float64
 13  x12     18398 non-null  float64
 14  x13     18398 non-null  float64
 15  x14     18398 non-null  float64
 16  x15     18398 non-null  float64
 17  x16     18398 non-null  float64
 18  x17     18398 non-null  float64
 19  x18     18398 non-null  float64
 20  x19     18398 non-null  float64
 21  x20     18398 non-null  float64
 22

In [4]:
# Remove time column
df = df.drop(['time'], axis=1)


In [5]:
X = df.drop(['y'], axis=1)
y = df['y']

In [6]:
X
X=X.fillna(0)
X

x1        x2        x3          x4        x5         x6  \
0      0.376665 -4.596435 -4.095756   13.497687 -0.118830 -20.669883   
1      0.475720 -4.542502 -4.018359   16.230659 -0.128733 -18.758079   
2      0.363848 -4.681394 -4.353147   14.127997 -0.138636 -17.836632   
3      0.301590 -4.758934 -4.023612   13.161566 -0.148142 -18.517601   
4      0.265578 -4.749928 -4.333150   15.267340 -0.155314 -17.505913   
...         ...       ...       ...         ...       ...        ...   
18393 -0.877441  0.786430  0.406426  135.301215  0.112295  26.300392   
18394 -0.843988  0.633086  0.561918  133.228949  0.141332  25.678597   
18395 -0.826547  0.450126  0.334582  134.977973  0.170370  25.056801   
18396 -0.822843  0.419383  0.387263  135.658942  0.199422  24.435005   
18397 -0.840981  0.582710  0.593416  136.339880  0.228460  24.712960   

             x7        x8        x9       x10  ...        x52       x53  \
0      0.000732 -0.061114 -0.059966 -0.038189  ...  10.091721  0.053279   
1      0.000732 -0.061114 -0.059966 -0.038189  ...  10.095871  0.062801   
2      0.010803 -0.061114 -0.030057 -0.018352  ...  10.100265  0.072322   
3      0.002075 -0.061114 -0.019986 -0.008280  ...  10.104660  0.081600   
4      0.000732 -0.061114 -0.030057 -0.008280  ...  10.109054  0.091121   
...         ...       ...       ...       ...  ...        ...       ...   
18393 -0.159185  0.058823 -0.080108 -0.038189  ...  -0.773514 -0.752385   
18394 -0.159185  0.058823 -0.080108 -0.038189  ...  -0.773514 -0.752385   
18395 -0.159185  0.048752 -0.080108 -0.038189  ...  -0.773514 -0.752385   
18396 -0.159185  0.048752 -0.080108 -0.038189  ...  -0.773514 -0.752385   
18397 -0.159185  0.048752 -0.070037 -0.038189  ...  -0.773514 -0.752385   

            x54        x55        x56       x57       x58       x59       x60  \
0     -4.936434 -24.590146  18.515436  3.473400  0.033444  0.953219  0.006076   
1     -4.937179 -32.413266  22.760065  2.682933  0.033536  1.090502  0.006083   
2     -4.937924 -34.183774  27.004663  3.537487  0.033629  1.840540  0.006090   
3     -4.938669 -35.954281  21.672449  3.986095  0.033721  2.554880  0.006097   
4     -4.939414 -37.724789  21.907251  3.601573  0.033777  1.410494  0.006105   
...         ...        ...        ...       ...       ...       ...       ...   
18393  2.682413   6.944644 -37.795661 -0.860218  0.010220  0.895685 -0.011242   
18394  2.683338   0.507755 -39.357199 -0.915698  0.010620  0.175348 -0.011235   
18395  2.684263   2.809146 -39.357199 -1.409596  0.013323  0.621020 -0.011228   
18396  2.685189   2.164859 -39.357199 -0.860218  0.012888  1.390902 -0.011221   
18397  2.686114   1.416690 -39.357199 -0.732044  0.012453  0.418993 -0.011214   

       x61  
0        0  
1        0  
2        0  
3        0  
4        0  
...    ...  
18393    0  
18394    0  
18395    0  
18396    0  
18397    0  

[18398 rows x 61 columns]

In [7]:
# Remove time column, and the categorical columns
X = X.drop(['x28', 'x61'], axis=1)

In [8]:
#X=X[['x3','x2','lag_1_x2','lag_1_x3','x2_pct_change','x18','x17','x3_pct_change','x16','rolling_mean_x16','lag_1_x16']]

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
X_train.shape, X_test.shape

((14718, 59), (3680, 59))

In [10]:
# Feature scaling

In [11]:
cols = X_train.columns

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

X_train = pd.DataFrame(X_train, columns=[cols])
X_test = pd.DataFrame(X_test, columns=[cols])


In [15]:
from xgboost import XGBClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from numpy import mean

# define model
model = XGBClassifier()

In [16]:
from imblearn.pipeline import Pipeline

from imblearn.combine import SMOTETomek
from imblearn.under_sampling import TomekLinks


In [17]:
# Define SMOTE-Tomek Links
resample=SMOTETomek(tomek=TomekLinks(sampling_strategy='majority'))
# Define pipeline
pipeline=Pipeline(steps=[('r', resample), ('m', model)])


In [18]:
clf_0 = pipeline.fit(X_train, y_train)


In [19]:
pred_y_0 = clf_0.predict(X_test)

print(accuracy_score(pred_y_0, y_test))



0.9967391304347826


In [20]:
target_names = ['class 0', 'class 1']
print(classification_report(y_test, pred_y_0, target_names=target_names))

# View confusion matrix for test data and predictions
confusion_matrix(y_test, pred_y_0)

              precision    recall  f1-score   support

     class 0       1.00      1.00      1.00      3662
     class 1       0.62      0.83      0.71        18

    accuracy                           1.00      3680
   macro avg       0.81      0.92      0.86      3680
weighted avg       1.00      1.00      1.00      3680



array([[3653,    9],
       [   3,   15]])

In [21]:
#enn

In [22]:
from imblearn.combine import SMOTEENN
from imblearn.under_sampling import EditedNearestNeighbours
# define model
model = XGBClassifier()

#Define SMOTE-ENN
resample=SMOTEENN(enn=EditedNearestNeighbours(sampling_strategy='all'))
#Define pipeline
pipeline=Pipeline(steps=[('r', resample), ('m', model)])

In [23]:
pipeline

Pipeline(steps=[('r',
                 SMOTEENN(enn=EditedNearestNeighbours(sampling_strategy='all'))),
                ('m',
                 XGBClassifier(base_score=None, booster=None, callbacks=None,
                               colsample_bylevel=None, colsample_bynode=None,
                               colsample_bytree=None,
                               early_stopping_rounds=None,
                               enable_categorical=False, eval_metric=None,
                               feature_types=None, gamma=None, gpu_id=None,
                               grow_policy=None, importance_type=None,
                               interaction_constraints=None, learning_rate=None,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=None, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, n_estimators=100,
                               n_jobs=None, num_parallel_tree=None,
                               predictor=None, random_state=None, ...))])

In [24]:
clf_2 = pipeline.fit(X_train, y_train)
pred_y_2 = clf_2.predict(X_test)

print(accuracy_score(pred_y_2, y_test))

0.9970108695652173


In [25]:
target_names = ['class 0', 'class 1']
print(classification_report(y_test, pred_y_2, target_names=target_names))

# View confusion matrix for test data and predictions
confusion_matrix(y_test, pred_y_2)

              precision    recall  f1-score   support

     class 0       1.00      1.00      1.00      3662
     class 1       0.63      0.94      0.76        18

    accuracy                           1.00      3680
   macro avg       0.81      0.97      0.88      3680
weighted avg       1.00      1.00      1.00      3680



array([[3652,   10],
       [   1,   17]])

In [26]:
#ADASYN

from imblearn.over_sampling import ADASYN
ada = ADASYN(random_state=42)
X_res, y_res = ada.fit_resample(X, y)

In [27]:
from collections import Counter
print('Resampled dataset shape %s' % Counter(y_res))

Resampled dataset shape Counter({0: 18274, 1: 18266})


In [28]:
model = XGBClassifier()

#Define ADASYN
resample=ADASYN(random_state=42)
#Define pipeline
pipeline=Pipeline(steps=[('r', resample), ('m', model)])

In [29]:
clf_2 = pipeline.fit(X_train, y_train)
pred_y_2 = clf_2.predict(X_test)

print(accuracy_score(pred_y_2, y_test))

0.9964673913043478


In [30]:
target_names = ['class 0', 'class 1']
print(classification_report(y_test, pred_y_2, target_names=target_names))

# View confusion matrix for test data and predictions
confusion_matrix(y_test, pred_y_2)

              precision    recall  f1-score   support

     class 0       1.00      1.00      1.00      3662
     class 1       0.60      0.83      0.70        18

    accuracy                           1.00      3680
   macro avg       0.80      0.92      0.85      3680
weighted avg       1.00      1.00      1.00      3680



array([[3652,   10],
       [   3,   15]])